name: dbt Analytics CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt DuckDB adapter
        run: |
          pip install dbt-duckdb

      - name: Run dbt Compile & Test
        working-directory: ./saas_analytics
        run: |
          dbt deps || true
          dbt compile